# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, unique=True, verbose_name='\u0443\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043a\u043b\u044e\u0447 \u043f\u0435\u0441\u043d\u0438')),
                ('song', models.TextField(blank=True, null=True, verbose_name='\u043f\u0435\u0441\u043d\u044f')),
            ],
        ),
    ]
